# Generated by Django 4.2.25 on 2025-10-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Связались')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки менеджера')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_date'],
            },
        ),
    ]
