# Generated by Django 4.2.26 on 2025-11-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_applicationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=500, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='twitter',
            field=models.CharField(blank=True, max_length=500, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='website',
            field=models.CharField(blank=True, max_length=500, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.CharField(blank=True, max_length=500, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter',
            field=models.CharField(blank=True, max_length=500, verbose_name='Twitter'),
        ),
    ]
