# Generated by Django 4.2.26 on 2025-11-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_url_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='tags',
            field=models.CharField(blank=True, help_text='Теги через запятую', max_length=500, verbose_name='Теги'),
        ),
    ]
