# Generated by Django 4.2.26 on 2025-11-23 19:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_insight_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержание'),
        ),
    ]
